version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Paris"
      
  - package-ecosystem: "cargo"
    directory: "/src-tauri/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/Paris"